ExerciciosVixTeam/Controllers/EmpresaController.cs
using ExerciciosVixTeam.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExerciciosVixTeam.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly ILogger<EmpresaController> _logger;

        public EmpresaController(ILogger<EmpresaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastrar()
        {
            var empresaModel = new EmpresaModel();
            if (ViewData["DadosEmpresa"] != null)
            {
                empresaModel = (EmpresaModel)ViewData["DadosEmpresa"];
            }
            return View(empresaModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Cadastro([Bind("Codigo, Nome, NomeFantasia, CNPJ")] EmpresaModel empresaModel)
        {
            ViewData["DadosEmpresa"] = empresaModel;
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
           return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

ExerciciosVixTeam/Controllers/PessoaModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExerciciosVixTeam.Data;
using ExerciciosVixTeam.Models;

namespace ExerciciosVixTeam.Controllers
{
    public class PessoaModelsController : Controller
    {
        private readonly ExerciciosVixTeamContext _context;

        public PessoaModelsController(ExerciciosVixTeamContext context)
        {
            _context = context;
        }

        // GET: PessoaModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.PessoaModel.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> AlterarStatus(int id)
        {
            var pessoaModel = await _context.PessoaModel.FindAsync(id);
            if (pessoaModel.Status.Equals("Ativo"))
            {
                pessoaModel.Status = "Inativo";
            }
            else
            {
                pessoaModel.Status = "Ativo";
            }
            _context.Update(pessoaModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: PessoaModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoaModel = await _context.PessoaModel
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (pessoaModel == null)
            {
                return NotFound();
            }

            return View(pessoaModel);
        }

        // GET: PessoaModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PessoaModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Nome,Email,DataNascimento,QuantidadeFilhos,Salario")] PessoaModel pessoaModel)
        {
            var pessoaEmail = _context.PessoaModel.Where(x => x.Email.Equals(pessoaModel.Email) && x.Codigo != pessoaModel.Codigo);
            if(pessoaEmail.Count() > 0)
            {
                ModelState.AddModelError("Regra de Negócio", "E-mail já Cadastrado!");
                return View(pessoaModel);
            }

            DateTime x = DateTime.Parse("01/01/1990");
            if (pessoaModel.DataNascimento < x)
            {
                ModelState.AddModelError("Regra de Negócio", "Data de Nascimento não pode ser inferior a 01/01/1990.");
                return View(pessoaModel);
            }

            pessoaModel.Status = "Ativo";
                _context.Add(pessoaModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
         
            return View(pessoaModel);
        }
      

    // GET: PessoaModels/Edit/5
    public async Task<IActionResult> Edit(int? id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var pessoaModel = await _context.PessoaModel.FindAsync(id);
            if (pessoaModel == null)
            {
                return NotFound();
            }
            return View(pessoaModel);
        }


        

        // POST: PessoaModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Codigo,Nome,Email,DataNascimento,QuantidadeFilhos,Salario,Status")] PessoaModel pessoaModel)
        {
            if (id != pessoaModel.Codigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //aqui
                var editPessoa = pessoaModel.Status;
                if(editPessoa == "Inativo")
                {
                    ModelState.AddModelError("Regra de Negócio", "Pessoas com Status INATIVO não podem ser editadas.");
                    return View(pessoaModel);
                }
              
               DateTime x = DateTime.Parse("01/01/1990"); 
               if (pessoaModel.DataNascimento < x)
                {
                    ModelState.AddModelError("Regra de Negócio", "Data de Nascimento não pode ser inferior a 01/01/1990.");
                    return View(pessoaModel);
                }
                try
                {
                    _context.Update(pessoaModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoaModelExists(pessoaModel.Codigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoaModel);
        }

        // GET: PessoaModels/Delete/5

       
        public async Task<IActionResult> Delete(int? id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var PessoaModel = await _context.PessoaModel
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (PessoaModel == null)
            {
                return NotFound();
            }

            return View(PessoaModel);
        }

        // POST: PessoaModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pessoaModel = await _context.PessoaModel.FindAsync(id);
            _context.PessoaModel.Remove(pessoaModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
       


        private bool PessoaModelExists(int id)
        {
            return _context.PessoaModel.Any(e => e.Codigo == id);
        }


    }
}

ExerciciosVixTeam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExerciciosVixTeam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExerciciosVixTeam.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a  asp-controller="Home"  asp-action="Index" class="nav-link px-2 text-secondary"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Exercicios VixTeam</font></font></a></li>
          <li><a  asp-controller="Home"  asp-action="Index" class="nav-link px-2 text-white"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Home</font></font></a></li>
          <li><a  asp-controller="Home"  asp-action="Privacy" class="nav-link px-2 text-white"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Privacy</font></font></a></li>
          
        </ul>

      

        <div class="text-end">
            <div class="dropdown">
                 <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Selecione
                 </button>
                 <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                     <li><a class="dropdown-item"  asp-controller="Empresa"  asp-action="Index">Empresa</a></li>
                     <li><a class="dropdown-item"asp-controller="PessoaModels"  asp-action="Index">Pessoa</a></li>
                 </ul>
            </div>
        </div>
      </div>
    </div>
  </header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ExerciciosVixTeam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>